FROM oven/bun:1

WORKDIR /use/project

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install
RUN bun run generate:db

EXPOSE 8080

CMD [ "bun","start:backend" ]