FROM oven/bun:1

WORKDIR /use/project

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/websocket ./apps/websocket

RUN bun install
RUN bun run generate:db

EXPOSE 8081

CMD [ "bun","start:websocket" ]