FROM oven/bun:1

WORKDIR /use/project

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install
RUN bun run generate:db

EXPOSE 3000

CMD ["sh", "-c", "bun run build && bun start:web"]
