name: Continuous deployment (prod) Backend
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build image and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./docker/Dockerfile.backend
                  push: true
                  tags: whoisasx/http-backend:${{github.sha}}
            - run: |
                  echo "${{ secrets.VM_SSH_KEY }}" &> ~/ssh_key
                  mkdir -p /home/runner/.ssh
                  ls /home/runner/.ssh
                  touch /home/runner/.ssh/known_hosts
                  echo "${{ secrets.VM_SSH_KEY }}" &> /home/runner/.ssh/known_hosts
                  chmod 700 /home/runner/ssh_key
                  ssh -o StrictHostKeyChecking=no -i ~/ssh_key sadil4064@34.100.154.26 -t "docker stop http-backend && docker run --name http-backend -d -p 8080:8080 whoisasx/http-backend:${{ github.sha }}"
